[project]
name = "python-practice"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Amir-zeb", email = "amirzeb695@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "pyaudio>=0.2.14",
    "pyttsx3>=2.99",
    "speechrecognition>=3.17.0",
]

[tool.uv]
package = false

[dependency-groups]
dev = [
    "mypy>=2.3.0",
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
]

[[tool.mypy.overrides]]
module = ["speech_recognition.*", "pyttsx3.*"]
ignore_missing_imports = true